#
# Copyright (c) 2015 Google, Inc
#
# SPDX-License-Identifier:      GPL-2.0+
#

obj-y += reset_rk3288.o
obj-y += sdram_rk3288.o
obj-y += syscon_rk3288.o

ifdef CONFIG_SPL_BUILD
obj-y += board-spl_rk3288.o
endif
